name: nt4
description: Dart implementation of the WPILib NT4 protocol
version: 1.3.0
repository: https://github.com/mjansen4857/nt4

environment:
  sdk: ^3.0.6

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  collection: ^1.18.0
  messagepack: ^0.2.1
  msgpack_dart: ^1.0.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  full_coverage: ^1.0.0
  coverage: ^1.6.3
